services:
  stirling-pdf:
    container_name: stirlingpdf
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest
    ports:
      - '9080:8080'
    volumes:
      - ./StirlingPDF/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - ./StirlingPDF/extraConfigs:/configs
      - ./StirlingPDF/customFiles:/customFiles/
      - ./StirlingPDF/logs:/logs/
      - ./StirlingPDF/pipeline:/pipeline/
    environment:    
      - LANGS=en_GB
    security:
      enableLogin: ${ENABLE_LOGIN} # set to 'true' to enable login   
      loginAttemptCount: ${COUNT} # lock user account after 5 tries
      loginResetTimeMinutes: ${TIMEOUT} # lock account for 2 hours after x attempts
    initialLogin:
      username: ${NAME}  # Initial username for the first login
      password: ${PASSWORD}  # Initial password for the first login
 
